# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr:
- main

stages:
- stage: Build
  jobs:
  - job: BuildReceiver
    variables:
      containerOutputPath: $(Pipeline.Worksapce)/container.tar.gz
    steps:
    - script: |
        mkdir $(containerOutputPath)
      displayName: Prepare workspace
    - script: |
        docker build . --tag solid/integrations/play-hq/webhook-receiver:$(Build.SourceVersion)
      display: Build container
    - script: |
        docker save --output $(containerOutputPath) solid/integrations/play-hq/webhook-receiver:$(Build.SourceVersion)
      display: Export container
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(containerOutputPath)
      displayName: Upload container