name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    environment: Development

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build src/Solid.Integrations.PlayHQ.WebhookReceiver/. --tag solid/integrations/play-hq/webhook-receiver:$GITHUB_SHA
    - name: Azure Login
      env:
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      run: |
        az login --service-principal --tenant $AZURE_TENANT_ID --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET
        az group create --name playhq-webhook-receiver-dev --location westus3
        az deployment group create --resource-group playhq-webhook-receiver-dev --name stage1_$GITHUB_RUN_ID\_$GITHUB_RUN_ATTEMPT\_$GITHUB_SHA --template-file deploy/stage1.bicep
        ACR_NAME=$(az deployment group show -g playhq-webhook-receiver-dev  -n stage1_$GITHUB_RUN_ID\_$GITHUB_RUN_ATTEMPT\_$GITHUB_SHA --query properties.outputs.containerRegistryLoginServer.value --output tsv)
        az acr login --name $ACR_NAME
        docker tag solid/integrations/play-hq/webhook-receiver:$GITHUB_SHA $ACR_NAME/solid/integrations/play-hq/webhook-receiver:$GITHUB_SHA
        docker push $ACR_NAME/solid/integrations/play-hq/webhook-receiver:$GITHUB_SHA
        az deployment group create --resource-group playhq-webhook-receiver-dev --name stage2_$GITHUB_RUN_ID\_$GITHUB_RUN_ATTEMPT\_$GITHUB_SHA --template-file deploy/stage2.bicep --parameters containerImage=$ACR_NAME/solid/integrations/play-hq/webhook-receiver:$GITHUB_SHA

